AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'RAP SPIKE Distribution'

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - staging
      - production
    Default: staging
    Description: Environment that can be added to resource names

Resources:

  ArtifactsBucket:
    DeletionPolicy: 'Delete'
    Metadata:
      Comment: 'Bucket to store code artifacts'
    Properties:
      AccessControl: 'Private'
      BucketName: !Sub 'ce-artifacts-${AWS::StackName}-${AWS::AccountId}'
    Type: 'AWS::S3::Bucket'

  RawBucket:
    DeletionPolicy: 'Delete'
    Metadata:
      Comment: 'Bucket to store raw content data'
    Properties:
      AccessControl: 'Private'
      BucketName: !Sub 'ce-raw-${AWS::StackName}-${AWS::AccountId}'
    Type: 'AWS::S3::Bucket'

  BakedBucket:
    DeletionPolicy: 'Delete'
    Metadata:
      Comment: 'Bucket to store baked content data'
    Properties:
      AccessControl: 'Private'
      BucketName: !Sub 'ce-baked-${AWS::StackName}-${AWS::AccountId}'
    Type: 'AWS::S3::Bucket'

  ResourcesBucket:
    DeletionPolicy: 'Delete'
    Metadata:
      Comment: 'Bucket to store resources referenced by content'
    Properties:
      AccessControl: 'Private'
      BucketName: !Sub 'ce-resources-${AWS::StackName}-${AWS::AccountId}'
    Type: 'AWS::S3::Bucket'

  RawBucketPolicy:
    Metadata:
      Comment: 'Bucket policy to allow cloudfront to access the data'
    Properties:
      Bucket: !Ref RawBucket
      PolicyDocument:
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: 'Allow'
            Principal:
              CanonicalUser: !GetAtt CfOriginAccessIdentity.S3CanonicalUserId
            Resource:
              - !Sub 'arn:aws:s3:::${RawBucket}/*'
    Type: 'AWS::S3::BucketPolicy'

  BakedBucketPolicy:
    Metadata:
      Comment: 'Bucket policy to allow cloudfront to access the data'
    Properties:
      Bucket: !Ref BakedBucket
      PolicyDocument:
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: 'Allow'
            Principal:
              CanonicalUser: !GetAtt CfOriginAccessIdentity.S3CanonicalUserId
            Resource:
              - !Sub 'arn:aws:s3:::${BakedBucket}/*'
    Type: 'AWS::S3::BucketPolicy'

  ResourcesBucketPolicy:
    Metadata:
      Comment: 'Bucket policy to allow cloudfront to access the data'
    Properties:
      Bucket: !Ref ResourcesBucket
      PolicyDocument:
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: 'Allow'
            Principal:
              CanonicalUser: !GetAtt CfOriginAccessIdentity.S3CanonicalUserId
            Resource:
              - !Sub 'arn:aws:s3:::${ResourcesBucket}/*'
    Type: 'AWS::S3::BucketPolicy'

  LambdaEdgeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../request-handler
      Role: !GetAtt LambdaEdgeFunctionRole.Arn
      Runtime: python3.7
      Handler: lambda_function.lambda_handler
      Timeout: 5
      AutoPublishAlias: live

  LambdaEdgeFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
        - "arn:aws:iam::aws:policy/service-role/AmazonS3ReadOnlyAccess"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AllowLambdaServiceToAssumeRole"
            Effect: "Allow"
            Action:
              - "sts:AssumeRole"
            Principal:
              Service:
                - "lambda.amazonaws.com"
                - "edgelambda.amazonaws.com"

  CfDistribution:
    Properties:
      DistributionConfig:
        Comment: !Sub '${Environment} - Distribution for RAP Spike'
        DefaultCacheBehavior:
          LambdaFunctionAssociations:
            - EventType: origin-request
              LambdaFunctionARN: !Ref LambdaEdgeFunction.Version
          AllowedMethods:
            - 'HEAD'
            - 'GET'
          CachedMethods:
            - 'HEAD'
            - 'GET'
          Compress: false
          DefaultTTL: 86400
          ForwardedValues:
            Cookies:
              Forward: 'none'
            Headers:
              - 'Origin'
            QueryString: false
          MaxTTL: 31536000
          MinTTL: 86400
          TargetOriginId: MainOrigin
          ViewerProtocolPolicy: 'redirect-to-https'
        DefaultRootObject: 'index.html'
        Enabled: true
        HttpVersion: 'http1.1'
        IPV6Enabled: false
        Origins:
          - DomainName: aws.amazon.com
            Id: MainOrigin
            CustomOriginConfig:
              OriginProtocolPolicy: match-viewer
        PriceClass: 'PriceClass_All'
    Type: 'AWS::CloudFront::Distribution'

  CfOriginAccessIdentity:
    Metadata:
      Comment: 'Access S3 bucket content only through CloudFront'
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: 'Access S3 bucket content only through CloudFront'
    Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'

Outputs:
  ArtifactsBucket:
    Description: 'CE Artifacts S3 Bucket'
    Value: !Ref ArtifactsBucket
  RawBucket:
    Description: 'CE Raw S3 Bucket'
    Value: !Ref RawBucket
  BakedBucket:
    Description: 'CE Baked S3 Bucket'
    Value: !Ref BakedBucket
  ResourcesBucket:
    Description: 'CE Resources S3 Bucket'
    Value: !Ref ResourcesBucket
  LambdaEdgeFunction:
    Description: Lambda@Edge handler for content
    Value: !Ref LambdaEdgeFunction.Version
  CfDistributionId:
    Description: 'Id for our cloudfront distribution'
    Value: !Ref CfDistribution
  CfDistributionDomainName:
    Description: 'Domain name for our cloudfront distribution'
    Value: !GetAtt CfDistribution.DomainName

